#################################################################################
 # Copyright (C) 2025 SAP SE
 #
 # Permission is hereby granted, free of charge, to any person obtaining
 # a copy of this software and associated documentation files (the
 # "Software"), to deal in the Software without restriction, including
 # without limitation the rights to use, copy, modify, merge, publish,
 # distribute, sublicense, and/or sell copies of the Software, and to
 # permit persons to whom the Software is furnished to do so, subject to
 # the following conditions:
 #
 # The above copyright notice and this permission notice shall be
 # included in all copies or substantial portions of the Software.
 # 
 # THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 # EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 # MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 # NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
 # LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 # OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 # WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 #
 # SPDX-License-Identifier: MIT
#################################################################################


---
{{- if .Values.keycloak.apirule.enabled }}
apiVersion: gateway.kyma-project.io/v2alpha1
kind: APIRule
metadata:
  name: {{ .Values.keycloak.fullnameOverride }}
spec:
  gateway: kyma-system/kyma-gateway
  hosts:
    - {{ .Values.keycloak.apirule.host }}
  service:
    name: {{ .Values.keycloak.fullnameOverride }}
    port: 80
  timeout: 360
  rules:
    - path: /*
      methods: {{- toYaml .Values.keycloak.apirule.methods | nindent 6 }}
      noAuth: true
  {{- if index .Values "aas-web-ui" "enabled" }}
  corsPolicy:
    allowMethods:
      - POST
      - GET
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    allowOrigins:
      {{- if and (index .Values "aas-web-ui" "ingress" "enabled") (index .Values "aas-web-ui" "apirule" "enabled") }}
      {{ fail "Both ingress and apirule enabled. Failing the pipeline." }}
      {{ else if index .Values "aas-web-ui" "ingress" "enabled" }}
      - prefix: https://{{ index .Values "aas-web-ui" "ingress" "host" }}
      {{- else if index .Values "aas-web-ui" "apirule" "enabled" }}
      - prefix: https://{{ index .Values "aas-web-ui" "apirule" "host" }}
      {{ end }}
    allowCredentials: true
  {{ end -}}
{{ end -}}
